export const exerciseIds = [
  "Barbell_Bench_Press_-_Medium_Grip",
  "Incline_Dumbbell_Press",
  "Wide-Grip_Lat_Pulldown",
  "Barbell_Full_Squat",
  "Romanian_Deadlift",
  "Pushups",
  "Pullups",
  "Seated_Cable_Rows",
  "Dumbbell_Shoulder_Press",
  "Side_Lateral_Raise",
  "Barbell_Curl",
  "Hammer_Curls",
  "Triceps_Pushdown",
  "Dips_-_Triceps_Version",
  "Leg_Press",
  "Leg_Extensions",
  "Lying_Leg_Curls",
  "Standing_Calf_Raises",
  "Plank",
  "Air_Bike",
] as const;
